adding infraview config and auto tf destroy

diff --git a/stack-nexus/pipeline/aws/pipeline.yml b/stack-nexus/pipeline/aws/pipeline.yml
--- a/stack-nexus/pipeline/aws/pipeline.yml
+++ b/stack-nexus/pipeline/aws/pipeline.yml
@@ -199,7 +199,8 @@ jobs:
         params:
           tfplan_path: tfstate/plan.json
 
-  # Merge and trigger an apply manually (no autostart of this job)
+
+  # Merge and trigger an apply whenever there is a terraform plan passed successfully
   - name: terraform-apply
     serial: true
     max_in_flight: 1
@@ -237,6 +238,7 @@ jobs:
         params:
           plan_run: true
           terraform_source: merged-stack/
+
 
   - name: deploy-nexus
     serial: true
@@ -337,8 +339,8 @@ jobs:
                     title: '[SUCCESS]'
                     title_link: 'https://console.cycloid.io/organizations/((customer))/projects/((project))/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_ID'
                     text: |
-                      Nexus Repository url :
-                      http://$nexus_ip:$nexus_port
+                      Nexus Repository url: http://$nexus_ip:$nexus_port
+                      Nexus Admin Password: $nexus_admin_password
 
             - put: cycloid-event
               params:
@@ -348,14 +350,21 @@ jobs:
                         The project ((project)) on ((env)) environment has been deployed successfully.
                         </br>
                         <ul>
-                        <li><em><a target="_blank" href="http://$nexus_ip:$nexus_port">Access to Nexus Repository</a></em></li>
+                        <li>Nexus Repository url: <em><a target="_blank" href="http://$nexus_ip:$nexus_port">http://$nexus_ip:$nexus_port</a></em></li>
+                        <li>Nexus Admin Password: $nexus_admin_password</li>
                         </ul>
                 title: The project ((project)) on ((env)) environment deployed successfully
+
 
   - name: post-deployment
     max_in_flight: 1
     build_logs_to_retain: 10
     plan:
+      - get: tfstate
+        trigger: true
+        passed:
+          - deploy-nexus
+
       - do:
         - task: configure-project-backends
           config:
@@ -370,14 +379,14 @@ jobs:
                 - '-c'
                 - |
                   echo "Login to Cycloid API:"
-                  return_code=$(cy login --org ${ORGANIZATION} --api-key ${API_KEY})
-                  if [[ "$return_code" != "200" && "$return_code" != "422" ]]; then
-                      echo "error, return code $return_code"
+                  cy login --org ${ORGANIZATION} --api-key ${API_KEY} >output
+                  if [[ "$?" != "0" ]]; then
+                      echo "Login Error: cy returned code $?"
                       cat output
                       exit 1
                   fi
                   echo "Configuring infraView:"
-                  return_code=$(cy external-backend create infraview AWSRemoteTFState \
+                  cy external-backend create infraview AWSRemoteTFState \
                   --org ${ORGANIZATION} \
                   --project ${PROJECT} \
                   --env ${ENV} \
@@ -385,34 +394,64 @@ jobs:
                   --bucket-name ${BUCKET_NAME} \
                   --bucket-path ${BUCKET_PATH} \
                   --region ${AWS_REGION} \
-                  --cred ${EXTERNAL_BACKEND_AWS_CRED_NAME})
-                  if [[ "$return_code" != "200" && "$return_code" != "422" ]]; then
-                      echo "error, return code $return_code"
+                  --cred ${EXTERNAL_BACKEND_AWS_CRED_NAME} >output
+                  if [[ "$?" != "0" ]]; then
+                      echo "Configuring InfraView Error: cy returned code $?"
                       cat output
                       exit 1
                   fi
+
           params:
             ORGANIZATION: ((customer))
             PROJECT: ((project))
             ENV: ((env))
             API_URL: ((cycloid_api_url))
-            API_KEY: ((api_key))
+            API_KEY: ((cycloid_api_key))
             BUCKET_NAME: ((terraform_storage_bucket_name))
             BUCKET_PATH: ((project))/((env))/((project))-((env)).tfstate
             AWS_REGION: ((aws_region))
             EXTERNAL_BACKEND_AWS_CRED_NAME: ((external_backend_aws_cred_name))
 
+
+  # Destroy the demo infrastructure after its creation (after a timer and every hour)
   - name: terraform-destroy
-    serial: true
     max_in_flight: 1
     build_logs_to_retain: 10
     plan:
       - in_parallel:
         - get: git_stack-terraform
           trigger: false
+          passed:
+            - terraform-plan
 
         - get: git_config-terraform
           trigger: false
+          passed:
+            - terraform-plan
+
+        - get: tfstate
+          trigger: true
+          passed:
+            - terraform-apply
+
+        # In case of fail, it will help to retry every 1h to make sure the terraform is destroyed
+        - get: every-1h
+          trigger: true
+
+      # Timer to make sure the infra is destroyed at least 1 hour after creation
+      - task: wait-a-bit
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: cycloid/cycloid-toolkit
+          run:
+            path: /bin/bash
+            args:
+              - '-ec'
+              - |
+                sleep 3600
 
       - task: merge-stack-and-config
         config:
@@ -432,3 +471,61 @@ jobs:
           terraform_source: merged-stack/
         get_params:
           action: destroy
+
+      - task: pipeline-cleanup
+        config:
+          platform: linux
+          image_resource:
+            type: docker-image
+            source:
+              repository: cycloid/cycloid-toolkit
+            run:
+              path: /bin/bash
+              args:
+                - '-c'
+                - |
+                  echo "Login to Cycloid API:"
+                  cy login --org ${ORGANIZATION} --api-key ${API_KEY} >output
+                  if [[ "$?" != "0" ]]; then
+                      echo "Login Error: cy returned code $?"
+                      cat output
+                      exit 1
+                  fi
+                  echo "Pause pipeline:"
+                  cy pipeline pause \
+                  --org ${ORGANIZATION} \
+                  --project ${PROJECT} \
+                  --env ${ENV} \
+                  --api-url ${API_URL} >output
+                  if [[ "$?" != "0" ]]; then
+                      echo "Pause Pipeline Error: cy returned code $?"
+                      cat output
+                      exit 1
+                  fi
+
+          params:
+            ORGANIZATION: ((customer))
+            PROJECT: ((project))
+            ENV: ((env))
+            API_URL: ((cycloid_api_url))
+            API_KEY: ((cycloid_api_key))
+
+    on_failure:
+      put: slack-alert
+      params:
+        env_file: tfstate-env/env
+        attachments:
+          - author_link: 'https://www.cycloid.io/'
+            author_name: cycloid.io
+            color: danger
+            title: '[FAILED]'
+            title_link: 'https://console.cycloid.io/organizations/((customer))/projects/((project))/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_ID'
+            pretext: Terraform destroy FAILED.
+            fallback: 'Fail to destroy Nexus Repository demo project'
+            fields:
+              - short: true
+                title: Project
+                value: ((project))
+              - short: true
+                title: Environment
+                value: ((env))
